add .circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,6 +2,7 @@ version: 2.1
 orbs:
   python: circleci/python@2.0.3
   aws-cli: circleci/aws-cli@5.2.0
+  ansible: circleci/ansible@2.1.0
 
 executors:
   ansible-executor:
@@ -24,9 +25,9 @@ jobs:
     steps:
       - checkout
       - aws-cli/setup:
-         aws_access_key_id: AWS_ACCESS_KEY_ID
-         aws_secret_access_key: AWS_SECRET_ACCESS_KEY
-         region: AWS_DEFAULT_REGION
+          aws_access_key_id: AWS_ACCESS_KEY_ID
+          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
+          region: AWS_DEFAULT_REGION
       - run:
          name: deploy-cloudformation
          command: |
@@ -56,17 +57,39 @@ jobs:
             sudo apt-get update
             sudo apt-get install -y python3-pip jq
             pip3 install awscli ansible
+
+      - aws-cli/setup:
+          aws_access_key_id: AWS_ACCESS_KEY_ID
+          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
+          region: AWS_DEFAULT_REGION
+
       - run:
-          name: Get EC2 Public IP and inventory
+          name: Get EC2 Public IP and inventory(retry)
           command: |
-            EC2_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=task13-cf-ec2" \
-              --query "Reservations[0].Instances[0].PublicIpAddress" \
-              --output text)
-            
+            for i in {1..10}; do
+              EC2_IP=$(aws ec2 describe-instances \
+                --filters "Name=tag:Name,Values=task13-cf-ec2" \
+                --query "Reservations[0].Instances[0].PublicIpAddress" \
+                --output text)
+
+              if [[ "$EC2_IP" != "None" ]]; then
+                echo "EC2 IP acquired: $EC2_IP"
+                break
+              fi
+
+              echo "Waitng for EC2 to acquire public IP..."
+              sleep 5
+            done
+
+            if [[ "$EC2_IP" == "None" ]]; then
+              echo "Failed to get EC2 IP"
+              exit 1
+            fi
+
             echo "[web]" > inventory
             echo "ec2-user@${EC2_IP} ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory
             cat inventory
+
       - run:
           name: Run Ansible Playbook
           command: |
